### PR TITLE
Added a dimmed version of the trackcolour

### PR DESCRIPTION
**Pull request by navelpluisje**
The select buttons with track colour are on full brightness in both the selected and unselected state. Therefor you're not able to see which track(s) is/are selected.
Added a dimmed version for the unselected tracks

### CODE REVIEW

**Comment by GeoffAWaddington** [comment]
Will revisit this after version 2.0 is released.

**Comment by navelpluisje** [comment]
Hmmm, didn't see all the code format changes. What formattig standard do you use for formatting the code?

**Comment by GeoffAWaddington** [comment]
Are you trying to push commits to GeoffAWaddington/CSICode ?

**Comment by navelpluisje** [comment]
Only by PR's. These, when you approve them, can be merged into your repo. I forked the repo, created a branch for the change and created this PR. But because XCode uses a different way of formatting code, all those changes also are in this branch. 

Within Front end projects I normaly do, it is common to share things like code-formatting etc in the project itself. This way everyone uses the same format style.

**Comment by GeoffAWaddington** [comment]
By PR’s I’m assuming you mean push requests ?

If so, the way it will be handled in CSI is by code review of the source with you and I, then manual merges by me.

**Comment by navelpluisje** [comment]
PR stands for Pull Request, not Push Request. It's a request for pulling my changes into your code.
Out of curiocity; why do manual merges if it can be done way easier?

**Comment by GeoffAWaddington** [comment]
I’m old school :)

I want to have a good long look at any chaages and their implications :)

**Pull request closed without merging**
